### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#29]
@ZhiPing-S

"hi , after i apply commit, it pop up message "Unable to commit", can you give me some advices ? thanks"

**Comment by JohnstonCode** [comment]
Can I have a few details please.

- VSCode Version:
- OS Version:
- Extension Version:
- System Language:

**Comment by ZhiPing-S** [comment]
@JohnstonCode 
VSCode Version: 1.18.0
OS Version: Win10
Extension Version: v0.9.0
System Language: Chineses

**Comment by JohnstonCode** [comment]
Thanks for the info.

Think this will be a slash issues. I am sure the windows paths are returned in the following format "C:\Projects\ProjectName" and VS code give file paths in the "Projects/ProjectName".

A simple replace of the slashes should fix this.

**Comment by ZhiPing-S** [comment]
{
		"name": "SGMW_SVN",
		"rootPath": "D:\\repository\\SGMW_2017\\src",
		"paths": [],
		"group": ""
	},

i think this is ok, right ?

**Comment by JohnstonCode** [comment]
It still will not work. The extension is trying to join two different styles of file paths.

**Comment by ZhiPing-S** [comment]
{
		"name": "SGMW_SVN",
		"rootPath": "D:/repository/SGMW_2017/src",
		"paths": [],
		"group": ""
	}
hi, after i fix the slashes, it still not work

**Comment by JohnstonCode** [comment]
If you do "svn info" from the command line what are the slashes like for "Working Copy Root Path"?

**Comment by ZhiPing-S** [comment]
it's "D:\repository"

**Comment by JohnstonCode** [comment]
Thanks for doing that.

Not sure what could be causing it.

I will have to debug later when I have my windows machine available.

**Comment by JohnstonCode** [comment]
Also, do your file names contain any Chineses characters?

**Comment by ZhiPing-S** [comment]
no

**Comment by ZhiPing-S** [comment]
i install both tortiveSVN and Apache-Subversion, does it conflict ?

**Comment by JohnstonCode** [comment]
That won't be causing an issue. It just uses "svn" from the PATH

**Comment by ZhiPing-S** [comment]
i run "svn commit in command line, it works fine.

**Comment by sir-marc** [comment]
I can not commit either.
I get the following error message in the devtools:
`Running the contributed command:'svn.commitWithMessage' failed.: Error: Running the contributed command:'svn.commitWithMessage' failed.
	at e.$executeContributedCommand (<Path to VS Code>\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:412111)`

VSCode Version: 1.18.0
OS Version: Win7
Extension Version: v0.10.0
System Language: English

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
