### ISSUE TITLE
SVN sidebar icon is disappeared when VS Code restarted

### ISSUE THREAD

**Issue by harrykulkin** [JohnstonCode/svn-scm#982]
- VSCode Version: 
- OS Version: Windows 10 / WSL2 / Ubuntu 18.04.1 LTS
- Extension Version: 2.11.4
- System Language: Korean
- SVN Version: 1.9.7

## Issue ##
With Remote Development (WSL2 or Docker Dev Container),
when VS Code restarted, SVN sidebar icon is disappeared
and there is no connections in source control menu.

I have to check out it manually to fix this problem.
But When VS Code starts up next time, it happens again.

## Steps to Reproduce ##

1. Install Remote Development package
2. Run Remote Development with WSL2
3. Install SVN extension
4. checkout source
5. Restart VS Code (and mostly automatically reconnect WSL2 remote session)

## SVN Output ##
```
Using svn "1.9.7" from "svn"
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/41946314/85658431-353ec800-b6ee-11ea-9b48-619705644809.png)

**Comment by solomchuk** [comment]
I'm seeing similar behaviour, but without any Remote extensions - I have stuff checked out locally on my machine.

[VS Code Help -> About]
1.48.0-insider (user setup)
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:50:56.947Z (11 hrs ago)
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

SVN extension: v2.11.5
SVN:  1.14.0 (r1876290)
---
I noticed that if I have outstanding changes in the local copy, committing them to the repo appears to "fix" the problem, i.e. the SVN icon re-appears in the sidebar and under Source Control I can see the usual buttons + commit message box.

**Comment by gatiba** [comment]
It happens all the time to me too: randomly sometimes, restarting the program, the icon disappears and the output window shows only what you can see in the attached screenshot.
Always randomly and just sometimes, after closing and restarting Visual Studio Code several times magically the icon reappears and i can use the extension.

![Screenshot_20200820_102439](https://user-images.githubusercontent.com/18282664/90743174-eec1b000-e2cf-11ea-9c9b-79700bc98b0c.png)

**Comment by th0ger** [comment]
Similar issue happened to me today. SVN extension worked yesterday, but now the SVN menu icon is gone (it shows briefly after startup), and source control wants to connect with git. (As the screenshot in the issue.)

TortoiseSVN told me that my .svn database got corrupt, so the SVN extension actually failed to load. This happens often when I mix use of Tortoise (from windows side) and VDCode/SVN (from WSL1 side). Solution: Checkout SVN from scratch.

VSCode Version: 1.48.1
OS Version: Windows 10 / WSL1 / Ubuntu 18.04.4 LTS
TortoiseSVN 1.13.1, Build 28686

**Comment by adx-git** [comment]
Same Problem on my side (without docker).
I can see the icon for a short moment after starting VSCode before it is gone.

VSCode Version: 1.50.0-insider
OS Version: Windows: 10.0.18363
SVN Extension Version: 2.12.4
TortoiseSVN: 1.14.0 Build 28885

When there was no SVN installed, I could see the icon, after installing the SVN, the problem occurred.

**Comment by th0ger** [comment]
@adx-git did you test my fix? Try to update with TortoiseSVN to check for corrupt db.

**Comment by adx-git** [comment]
> 
> 
> @adx-git did you test my fix? Try to update with TortoiseSVN to check for corrupt db.

Actually I did not, because it was a "new" installation and I did not use SVN on this machine before.
Using the add-on was my first attempt to checkout the code.

**Comment by Macyrate** [comment]
This issue even made me think that the plugin does not support Linux ...

**Comment by mraandrews** [comment]
Same as everyone else, was starting to use vscode last week for some work, freshly updated that and installed the SVN plugin, I have the svn cli, but not tortoise. When first installed the icon o use is there, but after a restart, it’s gone! gone back to using eclipse as my company uses both svn and Git! Shame really!

**Comment by martinnikolov93** [comment]
Same happened to me when I had my PC restarted and OS update occurred. After that SVN in VSCode was showing for a second and then dissapear. 

I fixed it by updating the tortoise svn and then from file explorer clicked "SVN Update", suddenly the SVN icon showed in VSCode and everything works as it should now.

**Comment by ozpavel** [comment]
Not sure it is related but the svn icon (extension) also disappears for me after vscode starts. Then the log shows the same as other people reported.
Using svn "1.14.1" from "svn"

However, after a little while it provides some output ...
[]$ svn info --xml
[]$ svn info --xml
[]$ svn info --xml e:\cygwin64\home\pavel\projects\ps_tmp\ps_app\
[]$ svn: warning: W155010: The node '/home/pavel/projects/ps_tmp/ps_app/e:\cygwin64\home\pavel\projects\ps_tmp\ps_app\' was not found.
[]$ svn: E200009: Could not display info for all targets because some targets don't exist[]$ svn info --xml e:\cygwin64\home\pavel\projects\ps_tmp\ps_app\

It looks like the cygwin path and Windows path to repository are combined into one path, of course, that does not exist.
cygwin path to repo: '/home/pavel/projects/ps_tmp/ps_app/
Windows path to repo: e:\cygwin64\home\pavel\projects\ps_tmp\ps_app\

used to work before, most likely cygwin, tortoise updates, however, not sure when exactly it started. 
perhaps give you some other clues what might be happening.

**Comment by ozpavel** [comment]
Another reason why my subversion extension disappeared was the invalid certificate of the repository.

I resolved running the same command the extension in the command prompt and resolving/accepting the certificate. After that the subversion extension is working again as expected.

---
"e:\Program Files\TortoiseSVN\bin\svn.exe" stat --xml --no-ignore --ignore-externals --show-updates

Error validating server certificate for 'https://svn.xxxxxxx.com.au:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: svn.xxxxxxx.com.au
 - Valid: from May  7 13:35:39 2022 GMT until Aug  5 13:35:38 2022 GMT
 - Issuer: R3, Let's Encrypt, US
 - Fingerprint: XX:XX:XX
(R)eject, accept (t)emporarily or accept (p)ermanently? p

**Comment by xeobit** [comment]
Hi, I noticed the same behaviour and fixed it by doing an SVN Update in explorer.
My guess is it has something to do with the credentials.

**Comment by mraandrews** [comment]
So tickets for bugs just get closed without fixing them, this is still an issue for me, and has clearly caused others issues.  I have stopped using VSCode for this reason for the SVN projects I work on.  Quite shocked that it's been closed, and with little explanation why.  'Closed as not planned'. Means nothing!

**Comment by JohnstonCode** [comment]
Feel free to submit a PR @mraandrews

**Comment by mraandrews** [comment]
Sorry, don't know what a PR is in this context!  surely the bug that has
been raised should be enough to have someone look at it and fix it!

**Comment by JohnstonCode** [comment]
Okay, checkout the project look through the code find the bug and provide me with a patch to fix it

**Comment by ECourtecuisse** [comment]
Hello, I'm facing the same issue today.
I'm using Tortoise v1.14.7.29687 (latest version as of today),
Visual Studio Code v1.91.1 (latest version as of today),
SVN extension v2.17.0 (latest version as of today).
I have verified that the command line tools option is installed and the Tortoise binary is included in my environment variables.
I've noticed that when a dependency is missing, the icon appears correctly, but when all prerequisites are met, the icon disappears or briefly appears when Visual Studio Code launches.
I observe that the only accessible command is checkout, but it doesn't work (nothing happens).
Has anyone managed to fix this issue today?
Thanks in advance,
